### ISSUE TITLE
Perf: Async operations in parallel wherever possible 

### ISSUE THREAD

**Issue by JayGhiya** [unoplat/unoplat-code-confluence#69]

**Comment by vipinshreyaskumar** [comment]
Quantify minuscular work to be parallelise and parallelise.

**Comment by JayGhiya** [comment]
- Functions of a class can be parallelised inside codebasesummary.py (line number 68) - https://github.com/unoplat/unoplat-code-confluence/blob/main/unoplat-code-confluence/unoplat_code_confluence/summary_parser/codebase_summary.py . Then it has to be awaited until all functions of that particular class are finished. Then Classes of a particular package can be parallelised - (line number 72) . Then similar for package - line number 75

**Comment by JayGhiya** [comment]
Parallelism has to be controlled through semaphore in asyncio and externalised for user to make sure he does not hit limits on his llm provider.

**Comment by JayGhiya** [comment]
#90 we are also including dspy suggest in the same issue as perf is affecting comprehension

**Comment by JayGhiya** [comment]
testing with gpt4o-mini.

**Comment by JayGhiya** [comment]
Resuming this work and trying to assign customised parallelism at class level with n:n instances of llm provider.
